In [55]:
import pandas as pd
import numpy as np

stuff = {
    'Coorporate':['Apple','Google','Meta','Apple','Google','Meta'],
    'Employees':['John','April','Wes','Beth','Justin','Steph'], 
    'Salary':[200, 220, 190, 130, 120, 150] }

my_df = pd.DataFrame(stuff)
my_df

  Coorporate Employees  Salary
0      Apple      John     200
1     Google     April     220
2       Meta       Wes     190
3      Apple      Beth     130
4     Google    Justin     120
5       Meta     Steph     150

In [26]:
def times1000(x):
    return format(x * 1000, ",d")

In [51]:
my_df.Salary = my_df.Salary.apply(times1000)

In [43]:
my_df["FullSalary"] = my_df.Salary.apply(lambda x: format(x * 1000, ",d"))

In [56]:
my_df.Salary.describe()

count      6.000000
mean     168.333333
std       40.702170
min      120.000000
25%      135.000000
50%      170.000000
75%      197.500000
max      220.000000
Name: Salary, dtype: float64

In [48]:
my_df.drop("FullSalary", axis=1, inplace=True)

In [76]:
def namer(x):
    return f'Codemy: {str(x)}'  # to make sure pandas does not add any strange chars such as \n to x

In [66]:
my_df[["Coorporate", "Employees"]].apply(namer2)

       Coorporate       Employees
0   Codemy: Apple    Codemy: John
1  Codemy: Google   Codemy: April
2    Codemy: Meta     Codemy: Wes
3   Codemy: Apple    Codemy: Beth
4  Codemy: Google  Codemy: Justin
5    Codemy: Meta   Codemy: Steph

In [65]:
def namer2(x):
    return 'Codemy: ' + x # x must be a string

In [77]:
my_df[["Coorporate", "Employees"]].map(namer)

       Coorporate       Employees
0   Codemy: Apple    Codemy: John
1  Codemy: Google   Codemy: April
2    Codemy: Meta     Codemy: Wes
3   Codemy: Apple    Codemy: Beth
4  Codemy: Google  Codemy: Justin
5    Codemy: Meta   Codemy: Steph

In [84]:
my_df.sort_values('Salary',ascending=False, inplace=True)

In [85]:
my_df

  Coorporate Employees  Salary
1     Google     April     220
0      Apple      John     200
2       Meta       Wes     190
5       Meta     Steph     150
3      Apple      Beth     130
4     Google    Justin     120