In [137]:
import pandas as pd
import numpy as mp
from numpy.random import randn

In [151]:
my_df = pd.read_csv('dog_data.csv')
my_df.head(3)

           Breed        Color  DogName  OwnerZip
0       COCKAPOO        BROWN  CHARLEY     15236
1   GER SHEPHERD  BLACK/BROWN   TACODA     15238
2  BELG MALINOIS      BRINDLE     EICH     15238

In [215]:
my_df.head(3)

   DogName          Breed        Color  OwnerZip
0  CHARLEY       COCKAPOO        BROWN     15236
1   TACODA   GER SHEPHERD  BLACK/BROWN     15238
2     EICH  BELG MALINOIS      BRINDLE     15238

In [180]:
my_df=my_df.set_index("DogName")

In [181]:
my_df

                             Breed              Color  OwnerZip
DogName
CHARLEY                   COCKAPOO              BROWN     15236
TACODA                GER SHEPHERD        BLACK/BROWN     15238
EICH                 BELG MALINOIS            BRINDLE     15238
ARROW                        MIXED        BLACK/BROWN     15104
OAKLEY         AM PIT BULL TERRIER        WHITE/BROWN     15139
...                            ...                ...       ...
WINSLOW               GOLDENDOODLE              BROWN     15044
ROCKY KALAKOS    YORKSHIRE TERRIER        BLACK/BROWN     15220
ELLIE                      LAB MIX  WHITE/BLACK/BROWN     15220
CLARENCE              GOLDENDOODLE              WHITE     15143
GRIFFIN          SHETLAND SHEEPDOG              BLACK     15136

[2670 rows x 3 columns]

In [188]:
my_df.iloc[1]

Breed       GER SHEPHERD
Color        BLACK/BROWN
OwnerZip           15238
Name: TACODA, dtype: object

In [211]:
my_df[(my_df.Color == "BROWN") | (my_df.Breed.str.contains("MIX"))][["Color","Breed"]]

                     Color               Breed
DogName
CHARLEY              BROWN            COCKAPOO
ARROW          BLACK/BROWN               MIXED
LEROI          WHITE/BROWN       DACHSHUND MIX
CHICKIE        WHITE/BROWN      LHASA APSO MIX
KING                 BROWN    AM PITT BULL MIX
...                    ...                 ...
MACY                 BROWN              PUGGLE
NINO                 BROWN  LABRADOR RETRIEVER
JACK           WHITE/BLACK  COCKER SPANIEL MIX
WINSLOW              BROWN        GOLDENDOODLE
ELLIE    WHITE/BLACK/BROWN             LAB MIX

[1030 rows x 2 columns]

In [213]:
my_df.reset_index(inplace=True)

In [214]:
my_df

            DogName                Breed              Color  OwnerZip
0           CHARLEY             COCKAPOO              BROWN     15236
1            TACODA         GER SHEPHERD        BLACK/BROWN     15238
2              EICH        BELG MALINOIS            BRINDLE     15238
3             ARROW                MIXED        BLACK/BROWN     15104
4            OAKLEY  AM PIT BULL TERRIER        WHITE/BROWN     15139
...             ...                  ...                ...       ...
2665        WINSLOW         GOLDENDOODLE              BROWN     15044
2666  ROCKY KALAKOS    YORKSHIRE TERRIER        BLACK/BROWN     15220
2667          ELLIE              LAB MIX  WHITE/BLACK/BROWN     15220
2668       CLARENCE         GOLDENDOODLE              WHITE     15143
2669        GRIFFIN    SHETLAND SHEEPDOG              BLACK     15136

[2670 rows x 4 columns]

In [220]:
my_df.DogName.dropna()

0             CHARLEY
1              TACODA
2                EICH
3               ARROW
4              OAKLEY
            ...
2665          WINSLOW
2666    ROCKY KALAKOS
2667            ELLIE
2668         CLARENCE
2669          GRIFFIN
Name: DogName, Length: 2669, dtype: object

In [224]:
my_df.loc[5]

DogName               BAILEY
Breed       SCOTTISH TERRIER
Color                  BLACK
OwnerZip               15129
Name: 5, dtype: object